### ISSUE TITLE
Does not handle OperationTypes

### ISSUE THREAD

**Issue by melinath** [ivelum/graphql-py#6] opened 2017-09-01 05:39 UTC
It looks like this library doesn't support having operation names as part of the query. For example, this works:

```
{
    hero {
        name
    }
}
```

while this does not:

```
query {
    hero {
        name
    }
}
```

Both should be valid according to the spec.

**Comment by melinath** [comment] 2018-06-15 03:34
I looked into this a little more and it looks like the lexer works fine; the problem is in the parser.

**Comment by stebunovd** [comment] 2018-06-20 17:33
fixed in version 0.7.1, already on PyPI. The problem was caused by the lack of support for anonymous queries. Thank you for flagging this!

**Closed by stebunovd** 2018-06-20 17:33 UTC
